services:
  - type: web
    name: pharmacy-api
    env: python
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

